---
# Disable transparent huge pages.
- block:
  - name: Create /usr/lib/systemd
    file: path=/usr/lib/systemd/system state=directory

  - name: Copy disable-thp service template
    template: src=disable-thp.service dest=/usr/lib/systemd/system/disable-thp.service
    notify:
     - systemctl daemon-reload
     - restart disable-thp
     - restart redis

  - name: Enable disable-thp
    systemd:
      name: disable-thp.service
      enabled: yes
      daemon_reload: yes

  tags: redis

- name: create directory for redis.conf
  file: path=/var/docker_volumes/redis/ state=directory

- name: copy redis.conf
  copy: src=redis.conf dest=/var/docker_volumes/redis/redis.conf
  tags: redis

- name: start redis docker image
  docker_container:
    name: redis
    image: redis:5
    state: started
    pull: yes
    restart: yes
    restart_policy: always
    volumes:
    - "/var/docker_volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf

- name: Allow overcommit_memory on boot
  lineinfile:
    dest: /etc/sysctl.conf
    line: "vm.overcommit_memory = 1"
  tags: redis

- name: Allow overcommit now
  command: sysctl vm.overcommit_memory=1
  changed_when: false
  tags: redis
