version: '3'
services:
  python:
    image: python:3
    user: 1000:1000
    working_dir: /opt/app
    env_file: docker.env
    ports:
    - 8000:8000
    volumes:
    - .:/opt/app
    command: /opt/app/venv/bin/python manage.py runserver 0.0.0.0:8000
