---
# Installs and configures ufw, which in turn uses iptables for firewall management

# ufw includes sensible icmp defaults
- name: Install ufw
  apt: pkg=ufw state=present
  tags: ufw

- name: Set firewall rules
  command: ufw allow {{ item }}
  register: ufw_result
  changed_when: "ufw_result.stdout.startswith('Rule')"
  with_items:
    - http/tcp
    - https/tcp
    - ssh/tcp
  tags: ufw

- name: Check status of ufw
  command: ufw status
  register: ufw_status
  changed_when: False  # never report as "changed"
  tags: ufw

- name: Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False  # never report as "changed"
  tags: ufw

- name: Enable ufw
  command: ufw --force enable
  when: "ufw_status.stdout.startswith('Status: inactive') or 'ENABLED=yes' not in ufw_config.stdout"
  tags: ufw

