---
- name: Remove old docker images & containers
  docker_prune:
    images: yes
    containers: yes

- name: get code from git
  git: 
    dest: /usr/local/src/unbreakout
    repo: https://github.com/dirkcuys/unbreakout.git
    version: "master"

- name: Build docker image
  docker_image:
    name: local/unbreakout
    build:
      path: /usr/local/src/unbreakout
      pull: yes
    tag: latest
    source: build
    force_source: yes
    state: present
