---
- name: zoom
  hosts: zoom
  become: yes
  become_method: sudo
  vars_files: 
  - vars/zoom.code27.co.za.yml
  roles:
  #- common
  #- users
  - docker-ubuntu
  - nginx-proxy
  - postgres
  - role: postgres-role
    vars:
      DB_NAME: unbreakout
      DB_USER: unbreakout
  - build-docker-image
  - django-app


