---
- name: zoom
  hosts: zoom
  become: yes
  become_method: sudo
  vars_files: 
  - vars/zoom.code27.co.za.yml
  roles:
  #- common
  - dockerxubuntu
  - nginx-proxy
  - build-docker-image
  - django-app
